// <auto-generated>
// Generated by ProvisionData.HaloPSA.ApiClient.Generator
// This focused context enables better trimming by only including related types.
// </auto-generated>

using System.Text.Json.Serialization;

namespace ProvisionData.HaloPSA.ApiClient;

[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Item))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Item>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ItemAccountsLink))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ItemAccountsLink>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ItemStock))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ItemStock>))]
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class HaloPsaItemJsonContext : JsonSerializerContext
{
}
