// <auto-generated>
// Generated by ProvisionData.HaloPSA.ApiClient.Generator
// This focused context enables better trimming by only including related types.
// </auto-generated>

using System.Text.Json.Serialization;

namespace ProvisionData.HaloPSA.ApiClient;

[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AreaAzureTenant))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AreaAzureTenant>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AreaChangeFreeze))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AreaChangeFreeze>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AreaField))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AreaField>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AreaItem))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AreaItem>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AreaNote))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AreaNote>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AreaPopup))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AreaPopup>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AreaRequestType))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AreaRequestType>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AreaRequestTypeRule))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AreaRequestTypeRule>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AreaSectionDetail))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AreaSectionDetail>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AreaToDo))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AreaToDo>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Customer))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Customer>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.CustomerList))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.CustomerList>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.CustomerView))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.CustomerView>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Site))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Site>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.SiteContact))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.SiteContact>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.SiteList))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.SiteList>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.SiteView))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.SiteView>))]
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class HaloPsaCustomerJsonContext : JsonSerializerContext
{
}
