// <auto-generated>
// Generated by ProvisionData.HaloPSA.ApiClient.Generator
// This focused context enables better trimming by only including related types.
// </auto-generated>

using System.Text.Json.Serialization;

namespace ProvisionData.HaloPSA.ApiClient;

[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ConfigCommit))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ConfigCommit>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ConfigCommitView))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ConfigCommitView>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Field))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Field>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FieldGroup))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FieldGroup>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FieldHelper))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FieldHelper>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FieldInfo))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FieldInfo>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FieldRoleRestriction))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FieldRoleRestriction>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ModuleSetup))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ModuleSetup>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.SetupTab))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.SetupTab>))]
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class HaloPsaConfigurationJsonContext : JsonSerializerContext
{
}
