// <auto-generated>
// Generated by ProvisionData.HaloPSA.ApiClient.Generator
// This focused context enables better trimming by only including related types.
// </auto-generated>

using System.Text.Json.Serialization;

namespace ProvisionData.HaloPSA.ApiClient;

[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AddressStore))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AddressStore>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AttachmentView))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AttachmentView>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AuvikTenantMod))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AuvikTenantMod>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.BulkEmail))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.BulkEmail>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Control))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Control>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Currency))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Currency>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.DateTimeZone))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.DateTimeZone>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ExternalLinkList))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ExternalLinkList>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ForethoughtDetails))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ForethoughtDetails>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.KeyPair))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.KeyPair>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.KeyPair2))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.KeyPair2>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.KeyPair3))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.KeyPair3>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.KeyPair4))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.KeyPair4>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.PartsLookupResult))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.PartsLookupResult>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.PrePayThreshold))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.PrePayThreshold>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.RoundRobinLog))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.RoundRobinLog>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ServSite))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ServSite>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.StdRequest))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.StdRequest>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.StripePaymentMethod))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.StripePaymentMethod>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Viewers))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Viewers>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.XType))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.XType>))]
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class HaloPsaCommonJsonContext : JsonSerializerContext
{
}
