// <auto-generated>
// Generated by ProvisionData.HaloPSA.ApiClient.Generator
// This focused context enables better trimming by only including related types.
// </auto-generated>

using System.Text.Json.Serialization;

namespace ProvisionData.HaloPSA.ApiClient;

[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AreaNote))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AreaNote>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Customer))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Customer>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.CustomerList))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.CustomerList>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.CustomerView))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.CustomerView>))]
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class HaloPsaCustomerJsonContext : JsonSerializerContext
{
}
