// <auto-generated>
// Generated by ProvisionData.HaloPSA.ApiClient.Generator
// This focused context enables better trimming by only including related types.
// </auto-generated>

using System.Text.Json.Serialization;

namespace ProvisionData.HaloPSA.ApiClient;

[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Asset))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Asset>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AssetList))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AssetList>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AssetView))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AssetView>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AssetApplications))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AssetApplications>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AssetChange))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AssetChange>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AssetMeterReading))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AssetMeterReading>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AssetRelationshipRestriction))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AssetRelationshipRestriction>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.AssetUserCount))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.AssetUserCount>))]
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class HaloPsaDeviceJsonContext : JsonSerializerContext
{
}
