// <auto-generated>
// Generated by ProvisionData.HaloPSA.ApiClient.Generator
// This focused context enables better trimming by only including related types.
// </auto-generated>

using System.Text.Json.Serialization;

namespace ProvisionData.HaloPSA.ApiClient;

[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.InvoiceDetail))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.InvoiceDetail>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.InvoiceHeader))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.InvoiceHeader>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.InvoiceTotals))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.InvoiceTotals>))]
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class HaloPsaInvoiceJsonContext : JsonSerializerContext
{
}
