// <auto-generated>
// Generated by ProvisionData.HaloPSA.ApiClient.Generator
// This focused context enables better trimming by only including related types.
// </auto-generated>

using System.Text.Json.Serialization;

namespace ProvisionData.HaloPSA.ApiClient;

[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Action))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Action>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ActionReaction))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ActionReaction>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ActionsList))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ActionsList>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ActionsView))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ActionsView>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultAdditionalAgents))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultAdditionalAgents>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultApproval))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultApproval>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultBudget))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultBudget>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultCommit))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultCommit>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultDraft))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultDraft>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultItem))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultItem>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultOLA))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultOLA>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultOLADates))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultOLADates>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultRuleMatch))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultRuleMatch>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultsDateDependencies))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultsDateDependencies>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultsForecasting))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultsForecasting>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultsList))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultsList>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultsMileStone))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultsMileStone>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultsTimeEntry))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultsTimeEntry>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultsView))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultsView>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultToDo))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultToDo>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultVector))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultVector>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.FaultVectorScore))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.FaultVectorScore>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Ticket))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Ticket>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.TicketArea))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.TicketArea>))]
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class HaloPsaTicketJsonContext : JsonSerializerContext
{
}
