// <auto-generated>
// Generated by ProvisionData.HaloPSA.ApiClient.Generator
// This focused context enables better trimming by only including related types.
// </auto-generated>

using System.Text.Json.Serialization;

namespace ProvisionData.HaloPSA.ApiClient;

[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Uname))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Uname>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Users))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Users>))]
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class HaloPsaUserJsonContext : JsonSerializerContext
{
}
