// <auto-generated>
// Generated by ProvisionData.HaloPSA.ApiClient.Generator
// This focused context enables better trimming by only including related types.
// </auto-generated>

using System.Text.Json.Serialization;

namespace ProvisionData.HaloPSA.ApiClient;

[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Company))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Company>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.CompanyList))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.CompanyList>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.CompanyView))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.CompanyView>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Organisation))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Organisation>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.OrganisationField))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.OrganisationField>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Supplier))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Supplier>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.SupplierOrderDetail))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.SupplierOrderDetail>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.SupplierOrderHeader))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.SupplierOrderHeader>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.SupplierOrderHeaderView))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.SupplierOrderHeaderView>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.SupplierOrderTotals))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.SupplierOrderTotals>))]
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class HaloPsaVendorJsonContext : JsonSerializerContext
{
}
