// <auto-generated>
// Generated by ProvisionData.HaloPSA.ApiClient.Generator
// This focused context enables better trimming by only including related types.
// </auto-generated>

using System.Text.Json.Serialization;

namespace ProvisionData.HaloPSA.ApiClient;

[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ConsignmentDetail))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ConsignmentDetail>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ConsignmentHeader))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ConsignmentHeader>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Item))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Item>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ItemAccountsLink))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ItemAccountsLink>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ItemAccountsLinkMigration))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ItemAccountsLinkMigration>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ItemDeviceDefaults))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ItemDeviceDefaults>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ItemGroup))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ItemGroup>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ItemGroupRestriction))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ItemGroupRestriction>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ItemId))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ItemId>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ItemRestriction))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ItemRestriction>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ItemStock))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ItemStock>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ItemSupplier))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ItemSupplier>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ItemTieredPricing))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ItemTieredPricing>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.StockBin))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.StockBin>))]
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class HaloPsaItemJsonContext : JsonSerializerContext
{
}
