// <auto-generated>
// Generated by ProvisionData.HaloPSA.ApiClient.Generator
// This focused context enables better trimming by only including related types.
// </auto-generated>

using System.Text.Json.Serialization;

namespace ProvisionData.HaloPSA.ApiClient;

[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Contract))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Contract>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ContractApproval))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ContractApproval>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ContractDetail))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ContractDetail>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ContractHeader))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ContractHeader>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ContractHeaderContract))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ContractHeaderContract>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ContractHeaderList))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ContractHeaderList>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ContractHeaderView))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ContractHeaderView>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ContractPeriod))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ContractPeriod>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ContractRule))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ContractRule>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ContractSchedule))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ContractSchedule>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ContractSchedulePlan))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ContractSchedulePlan>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ContractTemplateDetail))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ContractTemplateDetail>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ContractTemplateHeader))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ContractTemplateHeader>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.ContractView))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.ContractView>))]
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class HaloPsaContractJsonContext : JsonSerializerContext
{
}
