// <auto-generated>
// Generated by ProvisionData.HaloPSA.ApiClient.Generator
// This focused context enables better trimming by only including related types.
// </auto-generated>

using System.Text.Json.Serialization;

namespace ProvisionData.HaloPSA.ApiClient;

[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Action))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Action>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Ticket))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Ticket>))]
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class HaloPsaTicketJsonContext : JsonSerializerContext
{
}
