// <auto-generated>
// Generated by ProvisionData.HaloPSA.ApiClient.Generator
// This focused context enables better trimming by only including related types.
// </auto-generated>

using System.Text.Json.Serialization;

namespace ProvisionData.HaloPSA.ApiClient;

[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.InvoiceChange))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.InvoiceChange>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.InvoiceDetail))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.InvoiceDetail>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.InvoiceDetailMeterTiers))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.InvoiceDetailMeterTiers>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.InvoiceDetailProRata))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.InvoiceDetailProRata>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.InvoiceDetailQuantity))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.InvoiceDetailQuantity>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.InvoiceDetailQuantityCriteria))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.InvoiceDetailQuantityCriteria>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.InvoiceHeader))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.InvoiceHeader>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.InvoiceHeaderMerge))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.InvoiceHeaderMerge>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.InvoiceHeaderView))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.InvoiceHeaderView>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.InvoicePaymentList))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.InvoicePaymentList>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.InvoiceTotals))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.InvoiceTotals>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.QuotationApproval))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.QuotationApproval>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.QuotationDetail))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.QuotationDetail>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.QuotationHeader))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.QuotationHeader>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.QuotationHeaderPdf))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.QuotationHeaderPdf>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.QuotationHeaderView))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.QuotationHeaderView>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.QuotationTotals))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.QuotationTotals>))]
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class HaloPsaInvoiceJsonContext : JsonSerializerContext
{
}
