// <auto-generated>
// Generated by ProvisionData.HaloPSA.ApiClient.DtosGenerator
// This focused context enables better trimming by only including related types.
// </auto-generated>

using System.Text.Json.Serialization;

namespace ProvisionData.HaloPSA.ApiClient;

[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Company))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Company>))]
[JsonSerializable(typeof(ProvisionData.HaloPSA.ApiClient.Models.Supplier))]
[JsonSerializable(typeof(List<ProvisionData.HaloPSA.ApiClient.Models.Supplier>))]
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class HaloPsaVendorJsonContext : JsonSerializerContext
{
}
